### ISSUE TITLE
something wrong with config.json?

### ISSUE THREAD

**Issue by cat5** [ultreia-io/migrate-redmine-to-gitlab#4]
So - can't seem to get passed 'init' - python version == 3.5.3 (debian stretch)

# cat config.json
{
 "redmine": { "url":"http://hostname.c.mygceproject.internal/redmine/projects/dsim", "key": "removed" },
 "gitlab": { "url":"https://gitlab.c.mygceproject.internal/product/dsim-import", "key": " removed" }
}

Error:

Traceback (most recent call last):
  File "/usr/local/bin/migrate-redmine-to-gitlab", line 11, in <module>
    load_entry_point('migrate-redmine-to-gitlab==2.0.2', 'console_scripts', 'migrate-redmine-to-gitlab')()
  File "/usr/local/lib/python3.5/dist-packages/migrate_redmine_to_gitlab-2.0.2-py3.5.egg/migrate_redmine_to_gitlab/commands.py", line 88, in main
  File "/usr/local/lib/python3.5/dist-packages/migrate_redmine_to_gitlab-2.0.2-py3.5.egg/migrate_redmine_to_gitlab/config.py", line 18, in __init__
KeyError: 'host'

Not sure why it's looking for a key named host.
Does the example need an update?

**Comment by cacciaresi** [comment]
I had the same issue with version 2.0.2, change _config.json_ like this to make it work:

```
{
  "redmine": { "host":"http://redmine.company.com", "path": "/projects/project_name", "key": "keyValue" },
  "gitlab": { "host":"https://gitlab.company.com", "path": "/user/project", "key": "keyValue" }  
}

```

**Comment by jeffi7** [comment]
Submitted a PR #6

**Comment by tchemit** [comment]
@jeffi7  Thanks for patch
